name : push events workflow

on : push 

jobs :
  unit-testing :
    runs-on: ubuntu-latest
    
    steps :
      - name : Checkout Code
        uses : actions/checkout@v2
        
      - name : Install PyTest 
        run  : pip install pytest
        
      - name : Run Test
        run  : pytest test.py 
       
       
