name : push events workflow

on : push 

jobs :
  unit-testing :
    runs-on: ubuntu-latest
    
    steps :
      - name : Checkout Code
        uses : actions/checkout@v2
        
      - name : Install PyTest 
        run  : pip install pytest
        
      - name : Run Test
        run  : pytest test.py 
        
      - name: Commit if Tests Pass
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v3
        with:
          commit_message: "Automated test success 🎉"
          branch: main
          commit_options: '--no-verify --signoff'
          
          repository: .
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
#           commit_user_name: Hassan-Ashfaq
#           commit_user_email: hassanashfaq20@gmail.com
       
